Home work 2
txt files committed in cf-1251 encoding for testing purposes

trying to process cf1251 txt files in encoding_issues.py script
1. by changing encoding (function in the same script). Tested separetely and was successfully done with process ending with code 0
2 then processing through the same functions, that were used for origin cf1251 files (functions imported from task_1_for_utf8.py; changes made: lines 26, 55, 62 parameter encoding='utf-8' added)

System error  message:

C:\Users\Armik\01_hmw\Scripts\python.exe D:/AI/_Python/Client_server_apps/homework/02_hmw/encoding_issues.py
Traceback (most recent call last):
  File "D:/AI/_Python/Client_server_apps/homework/02_hmw/encoding_issues.py", line 3, in <module>
    from task_1_for_utf8 import *
  File "D:\AI\_Python\Client_server_apps\homework\02_hmw\task_1_for_utf8.py", line 74, in <module>
    write_to_csv(my_source_list, my_pattern_list, file_destination)
  File "D:\AI\_Python\Client_server_apps\homework\02_hmw\task_1_for_utf8.py", line 54, in write_to_csv
    data_columns, data_values, val_grouped_by_column = get_data(file_source_list, pattern_list)
  File "D:\AI\_Python\Client_server_apps\homework\02_hmw\task_1_for_utf8.py", line 26, in get_data
    for line in open(file_source, 'rt', encoding='utf-8'):
  File "C:\Program Files (x86)\Python38-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 0: invalid continuation byte

Process finished with exit code 1